FROM php:8.1-apache
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
COPY . /var/www/html
RUN sed -i "s/\$dbPassword = \".*\";/\$dbPassword = \"codepass\";/" /var/www/html/config.php && \
docker-php-ext-install mysqli && \
docker-php-ext-enable mysqli 
EXPOSE 80
